version: "3"

services:
  db:
    container_name: pg-docker
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=minesweeper
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sweeper_network

  api:
    container_name: api
    build:
      context: ./server
    ports:
      - "8080:8080"
    networks:
      - sweeper_network
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING=postgresql://postgres:docker@db:5432/minesweeper
    volumes:
      - type: bind
        source: ./server
        target: /src
    command: npm run dev

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - sweeper_network
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./client
        target: /app

networks:
  sweeper_network:
    driver: bridge

volumes:
  db_data:
